### ISSUE TITLE
Sentry Dart Plugin - GA - plan

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart-plugin#43]
- [X] [Tests/Integration tests](https://github.com/getsentry/sentry-dart-plugin/issues/14) and https://github.com/getsentry/sentry-dart-plugin/pull/52
- [X] [Publish via Craft/Publish](https://github.com/getsentry/craft/issues/264) (there's a [bug](https://github.com/dart-lang/pub/issues/3307))
- [ ] [Documentation on sentry.io/docs and Wizard](https://github.com/getsentry/sentry-dart-plugin/issues/83)
- [ ] [Support --dart-define](https://github.com/getsentry/sentry-dart-plugin/issues/81) (nice to have)
- [X] [Support set-commits](https://github.com/getsentry/sentry-dart-plugin/issues/19) (nice to have) - #62 
- [ ] [Support sentry.properties](https://github.com/getsentry/sentry-dart-plugin/issues/42) (nice to have)

**Comment by vaind** [comment]
The plugin currently uses current directory as the base for `upload-dif`. I think this should be changed to `build`, even despite the reason given in the comment (that users can export debug symbols to a different dir). I think so because currently all binaries from the dart build directory (.dart_tool) are uploaded. In normal apps, there may be a lot of unnecessary stuff and tools. As an example - here's a list of uploaded files from the e integraton-test app - e.g. sentry-cli & those .bin files shouldn't be uploaded at all. 
```
  CMakeDetermineCompilerABI_C.bin: count=8 chunks=8
  CMakeDetermineCompilerABI_CXX.bin: count=8 chunks=8
  libapp.so: count=6 chunks=6
  libflutter.so: count=6 chunks=10
  libhello_santry.so: count=12 chunks=12
  libhello_santry.so.sym: count=4 chunks=4
  sentry-cli.exe: count=1 chunks=2
```

Similarly, if the app uses integration tests (which would build apps itself), those would be uploaded as well.

**Comment by vaind** [comment]
Similarly, if including sources, only the `lib` directory should be included IMO.

**Comment by marandaneto** [comment]
> there may be a lot of unnecessary stuff and tools

Yes, this is indeed a problem, but if there are crashes coming from dependencies, or Flutter itself, the symbols won't be in the `build` folder most likely, I guess?

> The plugin currently uses current directory as the base for upload-dif. I think this should be changed to build, even despite the reason given in the comment (that users can export debug symbols to a different dir)

That will make the plugin useless by default since examples of this command already use a sibling folder of `build`.

**Comment by marandaneto** [comment]
Closing it since each item of the checklist has its own issue.
